<a href="https://colab.research.google.com/github/Cristian-Larzabal/Data_science/blob/main/PrimerEntrega/ProyectoDS_ParteI_Larzabal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Primera Entrega
Archivo: ProyectoDS_ParteI_Larzabal.ipynb

In [ ]:
Abstract

Este proyecto utiliza el dataset “Melbourne Housing Snapshot” proveniente de Kaggle, que contiene información de más de 30.000 propiedades vendidas en Melbourne, Australia. La base de datos incluye características de las propiedades como tipo de vivienda, precio de venta, cantidad de dormitorios y baños, superficie de construcción y del terreno, ubicación (suburbio, distancia al centro), año de construcción, entre otras variables relacionadas con el entorno y la propiedad.

El objetivo del proyecto es explorar el mercado inmobiliario de Melbourne desde una perspectiva descriptiva y visual, respondiendo preguntas sobre la distribución de precios, la relación entre características de las propiedades y su valor, y la variación por suburbios y tipos de vivienda. Para ello se aplican técnicas de análisis univariado, bivariado y multivariado, utilizando herramientas como Matplotlib, Seaborn y pandas.

In [ ]:
Preguntas / Hipótesis de interés

In [ ]:
Objetivo del Proyecto

In [ ]:
Visualizaciones y Análisis

In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Cargar datos
df = pd.read_csv('https://raw.githubusercontent.com/Cristian-Larzabal/Data_science/refs/heads/main/PrimerEntrega/melb_data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [10]:
missing = df.isna().sum().sort_values(ascending=False)
missing[missing > 0]

BuildingArea    6450
YearBuilt       5375
CouncilArea     1369
Car               62
dtype: int64